[env:LUST-LINMOT]
board = esp32-s3-canfuck

build_type = debug
lib_ldf_mode = chain+
check_tool = clangtidy

build_flags = 
    ${env.build_flags}
    
# Motor properties
    -D BOARD_STEP_PER_REV=2000       # 2000 steps per revolution
    -D BOARD_PULLEY_TEETH=20         # 20 teeth on the pulley
    -D BOARD_INVERT_DIRECTION=true   # invert direction of the motor or S6
    -D BOARD_KEEP_OUT=5.0            # keep out distance in mm
    -D BOARD_SENSORLESS_TRIGGER=5.0  # trigger percentage for sensorless homing (Torque or Current)
    -D BOARD_BELT_PITCH=2            # belt pitch in mm
    -D BOARD_MAX_RPM=3000.0          # maximum RPM
    -D BOARD_MAX_ACCELERATION=100000 # maximum acceleration in mm/s^2
    -D BOARD_ENABLE_ACTIVE_LOW=true  # enable pin is active low

# Pin definitions
    -D BOARD_STEP_PIN=14        # step pin
    -D BOARD_DIRECTION_PIN=27   # direction pin
    -D BOARD_ENABLE_PIN=26      # enable pin
    -D BOARD_ALARM_PIN=13       # alarm pin
    -D BOARD_IN_POSITION_PIN=4  # in position pin
    -D BOARD_ENDSTOP_PIN=12     # endstop pin
    -D BOARD_ADC_PIN_CURRENT=36 # current sensor ADC pin
    -D BOARD_ADC_PIN_VOLTAGE=39 # voltage sensor ADC pin
    -D BOARD_MODBUS_RX_PIN=16   # modbus rx pin
    -D BOARD_MODBUS_TX_PIN=17   # modbus tx pin
    -D BOARD_NEOPIXEL_PIN=25    # neopixel data pin

# Current sensor properties
    -D BOARD_AMPERE_PER_MILLIVOLT=2.5e-3     # ADC conversion factor current reading: 2.5mA per mV
    -D BOARD_AMPERE_OFFSET_IN_MILLIVOLT=1666 # ADC offset in mV for 0A
    -D BOARD_VOLT_PER_MILLIVOLT=4.0e-2       # ADC conversion factor voltage reading: 40mV per V
    -D BOARD_MAX_AMPERE=5.0                  # maximum range current sensor in Ampere
    -D BOARD_MAX_VOLTAGE=40.0                # maximum range voltage sensor in Volt

# Available motor drivers - VIRTUAL driver is enabled by default
    -D DRIVER_GENERIC_STEPPER=1   # Generic stepper driver with endstop switch
    -D DRIVER_OSSM_REF_BOARD_V2=1 # OSSM Reference Board V2 with sensorless homing via current sensor

upload_protocol = esp-builtin

debug_tool = esp-builtin
debug_load_mode = manual

upload_port = COM13

monitor_port = ${dev_settings.monitor_port}
monitor_speed = ${dev_settings.monitor_speed}
monitor_filters = esp32_exception_decoder, colorize

