[env:OSSMRefBoard4MB]
board = esp32dev
board_build.mcu = esp32
board_build.partitions = no_ota.csv
build_flags = 
    ${env.build_flags}
    -D OSSM_REF
    -D FT_DOWNLOAD_FIRMWARE=0

# Motor properties
    -D STEP_PER_REV=2000       # 2000 steps per revolution
    -D PULLEY_TEETH=20         # 20 teeth on the pulley
    -D INVERT_DIRECTION=true   # invert direction of the motor or S6
    -D KEEP_OUT=5.0            # keep out distance in mm
    -D SENSORLESS_TRIGGER=5.0  # trigger percentage for sensorless homing (Torque or Current)
    -D BELT_PITCH=2            # belt pitch in mm
    -D MAX_RPM=3000.0          # maximum RPM
    -D MAX_ACCELERATION=100000 # maximum acceleration in mm/s^2
    -D ENABLE_ACTIVE_LOW=true  # enable pin is active low

# Pin definitions
    -D STEP_PIN=14        # step pin
    -D DIRECTION_PIN=27   # direction pin
    -D ENABLE_PIN=26      # enable pin
    -D ALARM_PIN=13       # alarm pin
    -D IN_POSITION_PIN=4  # in position pin
    -D ENDSTOP_PIN=12     # endstop pin
    -D ADC_PIN_CURRENT=36 # current sensor ADC pin
    -D ADC_PIN_VOLTAGE=39 # voltage sensor ADC pin
    -D MODBUS_RX_PIN=16   # modbus rx pin
    -D MODBUS_TX_PIN=17   # modbus tx pin
    -D NEOPIXEL_PIN=25    # neopixel data pin

# Current sensor properties
    -D AMPERE_PER_MILLIVOLT=2.5e-3     # ADC conversion factor current reading: 2.5mA per mV
    -D AMPERE_OFFSET_IN_MILLIVOLT=1666 # ADC offset in mV for 0A
    -D VOLT_PER_MILLIVOLT=4.0e-2       # ADC conversion factor voltage reading: 40mV per V
    -D MAX_AMPERE=5.0                  # maximum range current sensor in Ampere
    -D MAX_VOLTAGE=40.0                # maximum range voltage sensor in Volt

# Available motor drivers - VIRTUAL driver is enabled by default
    -D DRIVER_GENERIC_STEPPER=1   # Generic stepper driver with endstop switch
    -D DRIVER_OSSM_REF_BOARD_V2=1 # OSSM Reference Board V2 with sensorless homing via current sensor
